safe: true
lsi: false
paginate: 5
title: "Occasionally Things are Considered"
name: "Occasionally Things are Considered"
description: "Jack's musings on the world"
url: http://chachi.github.io
markdown: redcarpet
highlighter: pygments
github: [Repository metadata]

navbarLinks:
  - [ "CV" , "/CV" , "Resume/CV", "fa-institution" ]
  - [ "about" , "/about" , "About", "fa-info-circle" ]

socialLinks:
  - [ "facebook" , "https://www.facebook.com/jack.morrison1" , "Facebook", "fa-facebook" ]
  - [ "gplus" , "https://plus.google.com/117441278046314358685/posts/p/pub" , "Google+", "fa-google-plus" ]
  - [ "instagram", "http://www.instagram.com/drrobotnikk/", "Instagram", "fa-instagram" ]
  - [ "twitter" , "https://twitter.com/jackmorrison" , "Twitter", "fa-twitter" ]
  - [ "linkedin" , "http://www.linkedin.com/in/morrisonjack/" , "LinkedIn", "fa-linkedin" ]
  - [ "github" , "https://www.github.com/chachi" , "Github", "fa-github"]

